name: "Coverage"
on: [push, pull_request]
jobs:
    run:
        permissions:
            checks: write
            pull-requests: write
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [10.x, 12.x, 14.x]

        steps:
            - uses: actions/checkout@v1

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v2

            # - name: Reporting test coverage
            #   uses: ArtiomTr/jest-coverage-report-action@v2
